--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ImperaZim/EasyEconomyTycoonAddon
build-by-default: true
branches:
- main
projects:
  EasyEconomyTycoonAddon:
    path: ""
    icon: "icon.png"
    libs:
    - src: ImperaZim/EasyEconomy/EasyEconomy
      version: 2.0.0
...
